### ISSUE TITLE
Error when building the project

### ISSUE THREAD

**Issue by chitrung218** [MarkoSagadin/MicroML#2]
Hi, 
Thanks for your great work!
I got the error when executing this command with the example hello_world_stm32f7 in the main MicroML folder:
```
make -C tensorflow/ -f ../archive_makefile test PROJECT=hello_world_stm32f7

make: Entering directory '/MicroML/tensorflow'
Project was not found, exciting!
```

And when executing this command, I got the following error:
```
make -f archive_makefile PROJECT=hello_world_stm32f7
make: *** No rule to make target 'projects/hello_world_stm32f7/microlite_build/tensorflow/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.o', needed by 'projects/hello_world_stm32f7/microlite_build/microlite.a'.
```
Please advise me how to resolve those above errors. 
Thank you.

**Comment by MarkoSagadin** [comment]
Hello chitrung218, thank you for showing an interest in my project. I remember that I changed the way how archive file microlite.a is created, but it seems that I did not update documentation 😅

So, first command is the old way and the second one is the new and correct way. 
Now, about the issue of the missing object file. 
It seems that documentation is again insufficient: you need to also build a hello_world example from tensorflow in order to download all required microcontroller specific libraries (CMSIS specially). 
You should run below command fron tensorflow directory:
`sudo make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge hello_world_bin `

This will download everything that is needed by MicroML and it should work. I will also test everything tomorrow and update the documentation. If you ran into any problem do not hesitate to open a issue.

**Comment by chitrung218** [comment]
Hi, 
Thanks for your reply.
I found more errors as follows.
1.  In new tensorflow, there is no file `tensorflow/tensorflow/lite/micro/micro_optional_debug_tools.cc` and with new downloaded CMSIS in tensorflow/lite/micro/tools/make/download/cmsis/CMSIS/NN/Source/PoolingFunctions , there is no file arm_max_pool_s8_opt.c`. Therefore, we should remove or comment these two files in archive_makefile (line 110 and 226). Then, we can successfully build microlite_build/microlite.a
2. File `all_ops_resolver.cc` is no longer in `tensorflow/tensorflow/lite/micro/kernel`, so it should be `#include "tensorflow/lite/micro/all_ops_resolver.h"` in line 21 `projects/hello_world_stm32f4/main_functions.cc'

**Comment by chitrung218** [comment]
When I go inside `projects/hello_world_stm32f7` to build the project, I got the error when executing `make Makefile` as follows.
```
LD	build/firmware.elf
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: build/main_functions.o: in function `setup':
/home/linuxdev/MicroML/projects/hello_world_stm32f7/main_functions.cc:53: undefined reference to `tflite::ErrorReporter::Report(char const*, ...)'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: /home/linuxdev/MicroML/projects/hello_world_stm32f7/main_functions.cc:59: undefined reference to `tflite::ErrorReporter::Report(char const*, ...)'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: /home/linuxdev/MicroML/projects/hello_world_stm32f7/main_functions.cc:78: undefined reference to `tflite::ErrorReporter::Report(char const*, ...)'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: build/main_functions.o: in function `loop':
/home/linuxdev/MicroML/projects/hello_world_stm32f7/main_functions.cc:106: undefined reference to `tflite::ErrorReporter::Report(char const*, ...)'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: build/output_handler.o: in function `HandleOutput(tflite::ErrorReporter*, float, float)':
/home/linuxdev/MicroML/projects/hello_world_stm32f7/output_handler.cc:21: undefined reference to `tflite::ErrorReporter::Report(char const*, ...)'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: microlite_build/microlite.a(all_ops_resolver.o): in function `tflite::AllOpsResolver::AllOpsResolver()':
all_ops_resolver.cc:(.text._ZN6tflite14AllOpsResolverC2Ev+0x22): undefined reference to `tflite::ops::micro::Register_ABS()'
......
```
Could you please check the file `rules.mk` or other makefiles?

Thank you.

**Comment by MarkoSagadin** [comment]
Last few commits solved the problems. I can now build both hello_world examples, however I could not test them as I do not have hardware with me. I updated tensorflow submodule to the latest release (2.4.1) and updated list of needed source files. I aslo updated the instructions in readme. You should know that test make rule where you build a binary that can run on the host computer is not working, due to CMSIS-NN files being present in source lists. I plan to fix this in the future.

Please pull the latest commit and confirm that everything is working fine.

**Comment by chitrung218** [comment]
Hi,
Thanks your great help!
I successfully compiled the `projects/hello_world_stm32' with make rule

And looking forward to a fix of test make rule. 

Regards,
